### ISSUE TITLE
User login with email

### ISSUE THREAD

**Issue by avenmia** [CodeforHawaii/HIERR#2]
Subtask 1: Users should be able to login with email. - High Priority 
* Login with email would be stored on the GeoDatabase
  * Check if tables need to be joined or related

Subtask 2: Possibly connecting groups based on their responses - Low Priority

**Comment by boobeh123** [comment]
May help with configuring pol.is:

https://github.com/pol-is/polis-documentation/blob/master/usage/Embedding.md

https://github.com/pol-is/polis-documentation/blob/master/usage/UserAuthorization.md
