### ISSUE TITLE
Add ZipCode validation

### ISSUE THREAD

**Issue by avenmia** [CodeforHawaii/HIERR#25]
In the ZipCode component, we are passing through whatever text is submitted in the ZipCode box. 
https://github.com/CodeforHawaii/HIERR/blob/9d611dd1f9e3be7e7d04e324c2977358c627d235/src/components/zipcode.tsx#L14

This issue is to add validation to make sure the user enters a valid ZipCode. 

Add a regex to check if the text the user entered is 5 digits.

**Comment by kmal808** [comment]
Resource: https://stackoverflow.com/questions/2577236/regex-for-zip-code
