### ISSUE TITLE
Retrieve Pol.is report data

### ISSUE THREAD

**Issue by avenmia** [CodeforHawaii/HIERR#3]
The data for Pol.is is stored on their database, but we are able to retrieve the data using http requests. 

This task is for retrieving data from Pol.is and storing what's necessary into a local database.

**Comment by dinoboy197** [comment]
Questions:
* Do we have a shared login to pol.is with any test data pre-populated?
* I heard that some folks have tried this already without success. Briefly, what approaches have been tried so far?

**Comment by avenmia** [comment]
@dinoboy197 

We don't at the moment. The Pol.is I have is linked to my personal account. We would need a shared email and can create a new shared Pol.is account here: https://pol.is/createuser

We'd need to do the following:
1. Create a shared email for us to use
2. Create the shared Pol.is account using that shared email
3. Create a new Pol.is questionnaire (Or multiple if we want to test out multiple Pol.is surveys)
4. Replace the current Pol.is survey with the new one in the application
5. Add a request to generate the results report
6. Use the results report ID to get data about the Pol.is survey

**Comment by avenmia** [comment]
We don't have access to the Pol.is api so this will be done as part of the data export process
